^define: &img_shape [ 512, 512 ]

data:
  img_size: *img_shape
  batch_size: 64


model:
  model_name: seresnet50
  learning_rate: 0.00001
  weight_decay: 0.00001
  sinkhorn_iter: 15
  sinkhorn_temp: 1.5
  img_size: *img_shape
  block_size: 128
  feature_size: 1024
  transformers_layers: 6
  group_conv: 8
  train_block_size: [128]

^trainer:
  accumulate_grad_batches: 4
  accelerator: gpu
  devices: auto
  max_epochs: 10
  precision: 32
  val_check_interval: 0.1
  num_sanity_val_steps: 2
  log_every_n_steps: 10
  sync_batchnorm: True
  gradient_clip_val: 1.0